### ISSUE TITLE
add on wont load

### ISSUE THREAD

**Issue by adama2933** [Osborw/uworld-batch-unsuspend#5]
using V11. each time i download this addon and restart anki, I get an error message saying:An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨UWorld Batch Unsuspend⁩':
⁨Traceback (most recent call last):

please help!

**Comment by Osborw** [comment]
@adama2933, could you send a screenshot of the error message? I haven't heard of this before. Also, which version of the anking app are you using?

**Comment by adama2933** [comment]
I am using v11. An add-on you installed failed to load. If problems
persist, please go to the Tools>Add-ons menu, and disable or delete the
add-on.


When loading '⁨UWorld Batch Unsuspend⁩':

⁨Traceback (most recent call last):

File "aqt/addons.py", line 230, in loadAddons

File "/Users/adamayoub/Library/Application
Support/Anki2/addons21/899971795/__init__.py", line 4, in <module>

from . import dialog

File "/Users/adamayoub/Library/Application
Support/Anki2/addons21/899971795/dialog.py", line 60, in <module>

def getTagsFromText(text: str) -> list[str]:

TypeError: 'type' object is not subscriptable

⁩

**Comment by Osborw** [comment]
Thanks! I've got some stuff going on, but I'll look into this within the next few days

**Comment by Osborw** [comment]
Hey @adama2933, I've [released a new version](https://github.com/Osborw/uworld-batch-unsuspend/pull/6) of the add-on that may solve your issue. Next time you restart Anki, it should prompt you to install this update. 

I believe you might be on an older version of Anki. You are using the v11 cards, but the Anki application has a couple different versions. Check the [Anki site](https://apps.ankiweb.net/), all the way to the bottom where the Downloads are, and you'll see something like below. I believe you are using Qt5. Qt6 is the most recent, and should make you more compatible with the newer add-ons.

![Screenshot from 2024-08-05 23-00-32](https://github.com/user-attachments/assets/61542655-8675-438f-86e6-28a3fbfbc0a6)

But, if you want to stay on your current version, give this new release a shot! There may be additional errors that I'll need to address, so provide the same error message/screenshot if you run into them. :)

**Comment by Osborw** [comment]
@adama2933 let me know if this has resolved or if you're running into anymore issues. Closing this Issue since it's becoming stale.
