### ISSUE TITLE
v12 not working for me

### ISSUE THREAD

**Issue by txchemd1627** [Osborw/uworld-batch-unsuspend#7]
I noticed that the step1 v12 pull isn't working again for me. For example, I tried to unsuspend UWorld question ID 119 and I got the "Tag not found" error, but it definitely exists in anking. I'm not sure if any of the tag organization has changed recently but here is a screenshot of where that question is. This UWorld ID isn't the only one that this is happening for either. Any help is greatly appreciated! 
![image](https://github.com/user-attachments/assets/f5f3729d-135b-4079-9340-a2d4b5273e0e)

![image](https://github.com/user-attachments/assets/b7c666c5-bc0c-45e7-8d75-123480cd86e0)

![image](https://github.com/user-attachments/assets/c208bdcd-2ab9-48e3-88f1-3f5824a8b555)

**Comment by Osborw** [comment]
This is great info! Thanks for letting me know and sending those screenshots. I'll take a look into this and get back to you

**Comment by Osborw** [comment]
@txchemd1627 I've released a fix with PR #6 that should resolve this issue. Anki should prompt you for an update of the add-on next time you open it. Let me know if you run into any issues!

**Comment by txchemd1627** [comment]
Looks like it is working again! thanks for the help!
